//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BeyondTrustConnector.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting", IsNullable=false)]
    public partial class session_list {
        
        private session_listSession[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("session")]
        public session_listSession[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSession {
        
        private string session_typeField;
        
        private string lseqField;
        
        private string durationField;
        
        private string external_keyField;
        
        private string custom_attributesField;
        
        private string session_chat_view_urlField;
        
        private string session_chat_download_urlField;
        
        private string file_transfer_countField;
        
        private string file_move_countField;
        
        private string file_delete_countField;
        
        private session_listSessionStart_time start_timeField;
        
        private session_listSessionEnd_time end_timeField;
        
        private session_listSessionJumpoint jumpointField;
        
        private session_listSessionPrimary_customer primary_customerField;
        
        private session_listSessionJump_group jump_groupField;
        
        private session_listSessionPrimary_rep primary_repField;
        
        private session_listSessionCustomer[] customer_listField;
        
        private session_listSessionRepresentative[] rep_listField;
        
        private session_listSessionEvent[] session_detailsField;
        
        private string lsidField;
        
        /// <remarks/>
        public string session_type {
            get {
                return this.session_typeField;
            }
            set {
                this.session_typeField = value;
            }
        }
        
        /// <remarks/>
        public string lseq {
            get {
                return this.lseqField;
            }
            set {
                this.lseqField = value;
            }
        }
        
        /// <remarks/>
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string external_key {
            get {
                return this.external_keyField;
            }
            set {
                this.external_keyField = value;
            }
        }
        
        /// <remarks/>
        public string custom_attributes {
            get {
                return this.custom_attributesField;
            }
            set {
                this.custom_attributesField = value;
            }
        }
        
        /// <remarks/>
        public string session_chat_view_url {
            get {
                return this.session_chat_view_urlField;
            }
            set {
                this.session_chat_view_urlField = value;
            }
        }
        
        /// <remarks/>
        public string session_chat_download_url {
            get {
                return this.session_chat_download_urlField;
            }
            set {
                this.session_chat_download_urlField = value;
            }
        }
        
        /// <remarks/>
        public string file_transfer_count {
            get {
                return this.file_transfer_countField;
            }
            set {
                this.file_transfer_countField = value;
            }
        }
        
        /// <remarks/>
        public string file_move_count {
            get {
                return this.file_move_countField;
            }
            set {
                this.file_move_countField = value;
            }
        }
        
        /// <remarks/>
        public string file_delete_count {
            get {
                return this.file_delete_countField;
            }
            set {
                this.file_delete_countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionStart_time start_time {
            get {
                return this.start_timeField;
            }
            set {
                this.start_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionEnd_time end_time {
            get {
                return this.end_timeField;
            }
            set {
                this.end_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionJumpoint jumpoint {
            get {
                return this.jumpointField;
            }
            set {
                this.jumpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionPrimary_customer primary_customer {
            get {
                return this.primary_customerField;
            }
            set {
                this.primary_customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionJump_group jump_group {
            get {
                return this.jump_groupField;
            }
            set {
                this.jump_groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionPrimary_rep primary_rep {
            get {
                return this.primary_repField;
            }
            set {
                this.primary_repField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("customer", IsNullable=false)]
        public session_listSessionCustomer[] customer_list {
            get {
                return this.customer_listField;
            }
            set {
                this.customer_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("representative", IsNullable=false)]
        public session_listSessionRepresentative[] rep_list {
            get {
                return this.rep_listField;
            }
            set {
                this.rep_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("event", IsNullable=false)]
        public session_listSessionEvent[] session_details {
            get {
                return this.session_detailsField;
            }
            set {
                this.session_detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lsid {
            get {
                return this.lsidField;
            }
            set {
                this.lsidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionStart_time {
        
        private string timestampField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionEnd_time {
        
        private string timestampField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionJumpoint {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionPrimary_customer {
        
        private string gsnumberField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gsnumber {
            get {
                return this.gsnumberField;
            }
            set {
                this.gsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionJump_group {
        
        private string typeField;
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionPrimary_rep {
        
        private string gsnumberField;
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gsnumber {
            get {
                return this.gsnumberField;
            }
            set {
                this.gsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionCustomer {
        
        private string usernameField;
        
        private string public_ipField;
        
        private string private_ipField;
        
        private string hostnameField;
        
        private string osField;
        
        private string gsnumberField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string public_ip {
            get {
                return this.public_ipField;
            }
            set {
                this.public_ipField = value;
            }
        }
        
        /// <remarks/>
        public string private_ip {
            get {
                return this.private_ipField;
            }
            set {
                this.private_ipField = value;
            }
        }
        
        /// <remarks/>
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        public string os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gsnumber {
            get {
                return this.gsnumberField;
            }
            set {
                this.gsnumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionRepresentative {
        
        private string usernameField;
        
        private string display_nameField;
        
        private string public_display_nameField;
        
        private string private_display_nameField;
        
        private string public_ipField;
        
        private string private_ipField;
        
        private string hostnameField;
        
        private string osField;
        
        private string session_ownerField;
        
        private string seconds_involvedField;
        
        private string gsnumberField;
        
        private string idField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                this.display_nameField = value;
            }
        }
        
        /// <remarks/>
        public string public_display_name {
            get {
                return this.public_display_nameField;
            }
            set {
                this.public_display_nameField = value;
            }
        }
        
        /// <remarks/>
        public string private_display_name {
            get {
                return this.private_display_nameField;
            }
            set {
                this.private_display_nameField = value;
            }
        }
        
        /// <remarks/>
        public string public_ip {
            get {
                return this.public_ipField;
            }
            set {
                this.public_ipField = value;
            }
        }
        
        /// <remarks/>
        public string private_ip {
            get {
                return this.private_ipField;
            }
            set {
                this.private_ipField = value;
            }
        }
        
        /// <remarks/>
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        public string os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public string session_owner {
            get {
                return this.session_ownerField;
            }
            set {
                this.session_ownerField = value;
            }
        }
        
        /// <remarks/>
        public string seconds_involved {
            get {
                return this.seconds_involvedField;
            }
            set {
                this.seconds_involvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gsnumber {
            get {
                return this.gsnumberField;
            }
            set {
                this.gsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionEvent {
        
        private string filenameField;
        
        private string filesizeField;
        
        private string bodyField;
        
        private session_listSessionEventPerformed_by performed_byField;
        
        private session_listSessionEventDestination destinationField;
        
        private session_listSessionEventData[] dataField;
        
        private string timestampField;
        
        private string event_typeField;
        
        /// <remarks/>
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public string filesize {
            get {
                return this.filesizeField;
            }
            set {
                this.filesizeField = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionEventPerformed_by performed_by {
            get {
                return this.performed_byField;
            }
            set {
                this.performed_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public session_listSessionEventDestination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public session_listSessionEventData[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string event_type {
            get {
                return this.event_typeField;
            }
            set {
                this.event_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionEventPerformed_by {
        
        private string typeField;
        
        private string gsnumberField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gsnumber {
            get {
                return this.gsnumberField;
            }
            set {
                this.gsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionEventDestination {
        
        private string typeField;
        
        private string gsnumberField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gsnumber {
            get {
                return this.gsnumberField;
            }
            set {
                this.gsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionEventData {
        
        private session_listSessionEventDataValue valueField;
        
        /// <remarks/>
        public session_listSessionEventDataValue value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.beyondtrust.com/sra/namespaces/API/reporting")]
    public partial class session_listSessionEventDataValue {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
