name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        file: BeyondTrustConnector/Dockerfile
        push: true
        tags: frodehus/beyondtrustconnector:latest
    - name: Build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        file: BeyondTrustConnector/Dockerfile
        push: true
        tags: frodehus/beyondtrustconnector:latest  
          
